In [2]:
import numpy as np

NORMALIZATION PROBLEM: 

- In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [8]:
x = np.random.random((5,5)) #generates random variables in 5x5 array 
mean = x.mean() #generates mean 
std = x.std() #generates the standard deviation 
X_normalized = (x - mean)/std #normalization 


#save as .npy
np.save("X_normalized.npy", X_normalized)


In [16]:
load = np.load("X_normalized.npy") #outputing
print(X_normalized)
print('mean: ', mean)
print('std: ', std)

[[ 0.57286995 -0.7409904   0.73197592  1.34198333 -1.83106817]
 [-1.14239942  0.83796362  1.04412054 -0.43598166  1.38943762]
 [-1.38710521  0.90599453 -0.00673291 -0.64204201  0.63200247]
 [-1.0371945  -0.14743868 -1.28721235  1.2143662  -1.30483132]
 [ 1.21331395 -0.01185768  1.22338319 -0.32480755 -0.80774945]]
mean:  0.613128759379074
std:  0.26182162740816356


DIVISIBLE BY 3 PROBLEM:

- Create the following 10 x 10 ndarray.Which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy


In [20]:
a = np.arange(1, 101) #outputs numbers 1-100
a = a.reshape(10,10) #generates the 10x10 array 
a = np.square(a) #squares the value of each variable

div_by_3 = a[a%3 == 0] #divides each variable by three

#save as .npy
np.save("div_by_3.npy", div_by_3)


In [24]:
load = np.load("div_by_3.npy") #outputing

print('squares: ', a)
print('divided by 3: ', div_by_3)

squares:  [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
divided by 3:  [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
